:Author: BrentynHa
:Email: brent.hanna@gmail.com
:Revision: 2.0
:License: Public Domain

= Project: Jake-Box

A jiffy little arduino based project that allows you to select brightness, set a night-timer, and even select different 
LED patterns all wrapped up in a convenient menu system.

============================================================================
== Step 1: Installation

Pull the code from 

== Step 2: Assemble the circuit

Assemble the circuit following the diagram schematic.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board & enjoy
============================================================================

=== Folder structure

....
 Jake-Box                 => Arduino sketch folder
  ├── lighting.ino        => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  ├── sketch.json         => json secret file
  ├── .git                => git required files
  ├── README.md           => git readme file
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a Opensource License.

=== Contributing
To contribute to this project please feel free to just make a detailed pull request, if you have any 
questions feel free to contact BrentynHa <brent.hanna@gmail.com>

=== BOM
|===
| ID | Part name       | Part number | Quantity | Amazon link
===============================================
| W1 | Jumper Wire     | 1234-abcd   | 10 | 
| W2 | USB-C PowerCord | 2345-asdf   | 01 |   
| L1 | LED STRIP       | .........   | -- |   
| A1 | Arduino Uno     | ABX00066    | 01 | 
| A2 | OSEPP Shield    | ABX00066    | 01 |
|===

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
